### PR TITLE
Fix #46: Back button is broken on page load.

### LINKED ISSUE #46: Back-button is broken when city is auto-selected
If no city is specified and Karlsruhe gets auto-selected then the back-button doesn't work: Pressing the back-button goes from `/#karlsruhe` to `/`, which automatically redirects to `/#karlsruhe`.

Solution: The auto-selection should not push a new history entry.

### PR DESCRIPTION
**Pull request by torfsen**
Fixed by only introducing a new history item when the city actually changes. If no city was previously set then the current history item is replaced.

Before merging, please test that the app is behaving correctly 

- on page load when no city is specified (Karlsruhe should be auto-selected but there should only be one history item)
- during city change via the dropdown
- during city change by manually updating the URL hash. This has three subcases:
    - remove the hash completely (e.g. `'#berlin'` -> `''`)
    - switch to another city (e.g. `'#berlin'` -> `'#essen'`)
    - specify a non-existing city (e.g. `'#berlin'` -> `'#foobar'`)

### CODE REVIEW

**Comment by dirkschumacher** [comment]
If I change `#karlsruhe` to `#wat`it changes automatically back to `#karlsruhe' but then it breaks the history. I can't go back anymore to the page that I visited before `#karlsruhe`. Everything else works fine.

**Comment by johnjohndoe** [comment]
@torfsen I rebased your branch on top of `master` so it's easier to review it.

**Comment by torfsen** [comment]
@dirkschumacher: Good catch, fixed.

**Comment by dirkschumacher** [comment]
Cool. I trust that it is working now. :shipit: hard.

**Comment by johnjohndoe** [comment]
@torfsen I rebased your branch on top of `master` so it's easier to review it.

File: js/main.js [hunk 1]
```diff
@@ -272,15 +271,26 @@ function getCityName() {
...
-    if (history.pushState) {
-        history.pushState(null, null, "#" + cityName);
+function updateUrlHash(cityID, newHistoryState) {
+    var hash = '#' + cityID;
+    if (newHistoryState) {
+        if (history.pushState) {
+            history.pushState(null, null, "#" + cityID);
+        } else {
+            window.location.hash = cityID;
+        }
```
Comment (johnjohndoe) [inline js/main.js]: Please extract the `if` block in a named function to increase readability:

``` js
function addHistoryEntry(cityID) {
    if (history.pushState) {
        history.pushState(null, null, "#" + cityID);
    } else {
        window.location.hash = cityID;
    }
}
```

File: js/main.js [hunk 2]
```diff
@@ -272,15 +271,26 @@ function getCityName() {
...
     } else {
-        window.location.hash = cityName;
+        if (history.replaceState) {
+            history.replaceState(null, null, hash);
+        } else {
+            // http://stackoverflow.com/a/6945614/857390
+            window.location.replace(('' + window.location).split('#')[0] + hash);
+        }
```
Comment (johnjohndoe) [inline js/main.js]: Please extract the `if` block in a named function to increase readability:

``` js
function updateHistoryEntry(cityID) {
    var hash = '#' + cityID;
    if (history.replaceState) {
        history.replaceState(null, null, hash);
    } else {
        // http://stackoverflow.com/a/6945614/857390
        window.location.replace(('' + window.location).split('#')[0] + hash);
    }
}
```

File: js/main.js [hunk 3]
```diff
@@ -317,26 +327,29 @@ function cityIdToLabel(s) {
...
  * Set the current city.
  *
- * `city` is the city ID.
+ * `cityID` is the new city's ID. If `newHistoryState` is true then a new
+ * entry in the browser's history is created for the change. Otherwise the
+ * current history entry is replaced.
  */
-function setCity(city) {
-    var filename = 'cities/' + city + '.json';
+function setCity(cityID, newHistoryState) {
```
Comment (johnjohndoe) [inline js/main.js]: Monadic functions are much easier to understand than dyadic functions. One could not guess what the boolean in `setCity(getHashCity(), false);` does without looking at the function declaration or even at the implementation. Therefore, if possible avoid more the one argument (especially boolean flags). If it is not possible to split the function into two separate functions then the function name should reflect the meaning of the second parameter.

Comment (johnjohndoe) [inline js/main.js]: @torfsen You can hide the boolean in a separate function:

``` js
function setCityWithNewHistoryEntry(cityID) {
    setCity(cityID, true);
}
```

and use this function whenever a history entry has to be created. This will also make the comments redundant since the function name describes the intended behavior.

For the `false` case I would check within `setCity()` if the parameter is set:

``` js
function setCity(cityID, createNewHistoryEntry) {
    createNewHistoryEntry = createNewHistoryEntry || false;
    // ...
```

Then all invocations outside of `setCity()` can be simplified to using one parameter as in `setCity(getHashCity());`

Comment (torfsen) [inline js/main.js]: Sorry, but I don't see how adding a new function that simply curries the existing function improves readability of the code. We're not talking about a function with 10+ parameters here. I'd rather have a single function with 5 well documented parameters than 5 functions with one parameter each. Plus I'd also have to document (and ideally test) the curried versions. I'd go with DRY + good docs.

Take `history.pushState` as an example: It has three parameters (two of which are mandatory) and it is [well documented](https://www.w3.org/TR/html5/browsers.html#dom-history-pushstate). I think that's much better than having `pushStateDataKeepTextKeepUrl`, `pushStateTextKeepDataKeepUrl`, `pushStateDataAndTextKeepUrl`, etc.

If you're ever running into the situation that a function's interface gets too complex because of many optional parameters then the proper JavaScript pattern would be to [pass the optional parameters via a map](http://www.openjs.com/articles/optional_function_arguments.php). However, with just two parameters that doesn't make sense in our situation.

Comment (johnjohndoe) [inline js/main.js]: Let's leave it this way. My point was only about: "One could not guess what the boolean in `setCity(getHashCity(), false);` does without looking at the function declaration or even at the implementation."

**Comment by johnjohndoe** [comment]
@torfsen I noticed that a history entry for Karlsruhe is created everytime I manually type in a wrong city name. This is not intended, right?

**Comment by torfsen** [comment]
@johnjohndoe Actually that is the behavior I intended: Entering an invalid ID is equivalent to entering the default ID, and entering an ID manually creates a new history entry.

I'm open for other suggestions how to handle that case but keep in mind that it's pretty much a rare corner case -- people will use existing links or the dropdown to change cities. So things shouldn't break when you enter an invalid ID manually but we also don't need to worry to much about the details.

**Comment by johnjohndoe** [comment]
Okay. Then I would rebase the branch and merge it.
